# Generated by Django 6.0.1 on 2026-01-09 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='translate',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='word',
            new_name='russian',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='created',
            new_name='time_create',
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'very easy'), (2, 'easy'), (3, 'medium'), (4, 'hard'), (5, 'very hard')], default=1),
        ),
    ]
