# Generated by Django 6.0.1 on 2026-01-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0002_rename_translate_card_english_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='english',
            new_name='translate',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='russian',
            new_name='word',
        ),
    ]
