# Generated by Django 6.0.1 on 2026-01-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0003_rename_english_card_translate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
    ]
