# Generated by Django 6.0.1 on 2026-01-25 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0004_card_is_learned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-time_create']},
        ),
        migrations.AlterField(
            model_name='card',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'very easy'), (2, 'easy'), (3, 'medium'), (4, 'hard'), (5, 'very hard')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_learned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
